### ISSUE TITLE
Please support CLI build

### ISSUE THREAD

**Issue by gcsideal** [ricardoquesada/vchar64#1]
I'm a Debian Developer and would like to have it in the distribution. But it would mean the project needs CLI build support. Any plans for (c)make build scripts?

**Comment by ricardoquesada** [comment]
Does Debian package the Qt development tools? (qmake and other tools).
this project is using them (QtCreator in particular). I think it is possible to compile it using qmake from command line.
How is Debian compiling QtCreator?

**Comment by ricardoquesada** [comment]
how to do CLI:
```
$ cd vchar64
$ mkdir build
$ cd build
$ qmake ..
$ make
```
