### ISSUE TITLE
CTRL+3 and CTRL+4 does't work in multicolor

### ISSUE THREAD

**Issue by B3L4** [ricardoquesada/vchar64#10]
I just grabbed the newest version and run into a problem:

When you edit in Charset mode and using multicolor you no longer able to use the:
CTRL+3 and
CTRL+4 
for color selection. The CTRL+1 and 2 works fine. We didn't had that problem in earlier version.

B3L4

**Comment by ricardoquesada** [comment]
thanks. do you remember which version you were using? v0.0.12? Because I think it was fixed in v0.0.13. Could you confirm that? Thanks.

**Comment by B3L4** [comment]
Sure I will but I'm at work right now 9:46am in New York so will let you know in about 12 hrs...

**Comment by ricardoquesada** [comment]
ok. no problem :)

**Comment by ricardoquesada** [comment]
similar to issue #15 
closing it as fixed.
