### ISSUE TITLE
load prg extention  as binary

### ISSUE THREAD

**Issue by alexgoldblat** [ricardoquesada/vchar64#20]
hi , i loaded C64  2x2 font and when i choose "*prg/*64c" it load it as binary file . means it not skips the first two address bytes and the file is corrupted.

**Comment by ricardoquesada** [comment]
could you please attach the file? Thanks!

**Comment by alexgoldblat** [comment]
i am sorry i tried but it disable  it here. maybe there is a block to *prg files.
i can send to your email if you want.
my email: alexgoldblat@gmail.com

**Comment by ricardoquesada** [comment]
closed as invalid.
