### ISSUE TITLE
copy & paste broken in v0.2.2

### ISSUE THREAD

**Issue by ricardoquesada** [ricardoquesada/vchar64#23]
copy & paste in tileset / charset broken in v0.2.2

http://csdb.dk/release/index.php?id=152628

**Comment by ricardoquesada** [comment]
fixed.

**Comment by VanessaE** [comment]
Copy/paste is broken again, v0.2.4-54 self-compiled on Debian Bookworm.  No errors, just nothing happens when I try to paste.
