### ISSUE TITLE
Request screen and color ram editor

### ISSUE THREAD

**Issue by eightbit6510** [ricardoquesada/vchar64#4]
Hi!
Your software recently got ported to the open pandora linux handheld and that's how I noticed it. 
I like it, it's a quick and easy char editor! Can I make some requests to make it even better? 

It would be great if the software had a full screen char editor as well as a color map editor! That would be so useful!
also, tiles for 1x2 and 4x4 character sets (letters) usually adc #$40 for the next character. 
I know it's probably designed for level editing or something but maybe by adding that you can expand the usability of your software. ;)

Thanks for creating this!

**Comment by ricardoquesada** [comment]
Thanks for the feedback.

- What do you mean by full screen char editor and color map ?

Do you mean the possibility to have a 40x25 editor with colors ?... If so, yeah. I can do that.

Regarding tiles, yes, you can change the size of the tile with "Command + T" (or Control + T) and have any sizes from 1x1 to 8x8.

**Comment by eightbit6510** [comment]
Hi Ricardo,

Thank you for replying.

Yes, I indeed mean a 40x25 screen editor with colors. Great that you can
make that :)
In regards to the tiles, I mean something else.

Your 4x4 tiles are like this:

@A
BC

Which is good enough for backgrounds etc. but if I were to program a 4x4
char letter for scroll texts for instance, it should look different


A(+$00)A(+$40)
A(+$80)A+($C0)

Or for a 1x2 Letter

A(+$00)
A(+$40)

I hope that's explained well enough :)

Thanks again m8!

Great work, keep the 64 alive!


2015-09-14 0:43 GMT+02:00 Ricardo Quesada <notifications@github.com>:

**Comment by ricardoquesada** [comment]
In the "Tile Properties" window (Ctrl + T) change the "distance between chars" options.
Set it to 32 or 64 for 2x2 tiles and you will have what you need.

**Comment by eightbit6510** [comment]
Awesome! Thank you :)

2015-09-14 19:42 GMT+02:00 Ricardo Quesada <notifications@github.com>:

**Comment by ricardoquesada** [comment]
v0.0.11 has map support and "one color per tile"... closing feature request.
