### ISSUE TITLE
build failures :(

### ISSUE THREAD

**Issue by mrdudz** [ricardoquesada/vchar64#49]
i am trying to build on gentoo (stable profile). i can build other QT projects fine, so i guess i have all the required stuff :)

after qmake/make it dies with:

g++ -c -pipe -Werror -O2 -Wall -W -D_REENTRANT -DGIT_VERSION=\"0.2.4-2-gab55\" -DVERSION=\"0.2.4\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I../../src -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -Isrc -Irelease -I. -I../../src -I. -o release/main.o ../../src/main.cpp
In file included from ../../src/state.h:26:0,
                 from ../../src/mainwindow.h:23,
                 from ../../src/main.cpp:20:
../../src/stateimport.h:197:5: error: identifier 'static_assert' is a keyword in C++11 [-Werror=c++0x-compat]
     static_assert (sizeof(CTMHeader4) == 24, "Size is not correct");
     ^
$ g++ --version
g++ (Gentoo 5.4.0-r3 p1.4, pie-0.6.5) 5.4.0

after i hacked -std=c++11 into makefile.release, it apparently goes a bit further, but not quite:

In file included from ../../src/main.cpp:20:0:
../../src/mainwindow.h:124:39: error: expected ';' at end of member declaration
     void closeEvent(QCloseEvent *event) Q_DECL_OVERRIDE;
                                       ^
../../src/mainwindow.h:124:41: error: 'Q_DECL_OVERRIDE' does not name a type
     void closeEvent(QCloseEvent *event) Q_DECL_OVERRIDE;
                                         ^
In file included from ../../src/main.cpp:21:0:
../../src/vchar64application.h:28:29: error: expected ';' at end of member declaration
     bool event(QEvent* event) Q_DECL_OVERRIDE;
                             ^
../../src/vchar64application.h:28:31: error: 'Q_DECL_OVERRIDE' does not name a type
     bool event(QEvent* event) Q_DECL_OVERRIDE;
                               ^
../../src/main.cpp: In function 'int main(int, char**)':
../../src/main.cpp:31:31: error: incomplete type 'QLocale' used in nested name specifier
     qtTranslator.load("qt_" + QLocale::system().name(),
                               ^
../../src/main.cpp:46:39: error: incomplete type 'QLocale' used in nested name specifier
     myappTranslator.load("vchar64_" + QLocale::system().name(),
                                       ^
../../src/main.cpp:61:9: error: 'class VChar64Application' has no member named 'setApplicationDisplayName'
     app.setApplicationDisplayName(QLatin1String("VChar64"));
         ^
In file included from ../../src/main.cpp:21:0:
../../src/vchar64application.h:31:10: error: 'void VChar64Application::fileOpenRequest(const QString&)' is protected
     void fileOpenRequest(const QString& file);
          ^
../../src/main.cpp:82:49: error: within this context
     QObject::connect(&app, &VChar64Application::fileOpenRequest, mainWin, &MainWindow::openFile);
                                                 ^
../../src/main.cpp:82:96: error: no matching function for call to 'QObject::connect(VChar64Application*, void (VChar64Application::*)(const QString&), MainWindow*&, bool (MainWindow::*)(const QString&))'
     QObject::connect(&app, &VChar64Application::fileOpenRequest, mainWin, &MainWindow::openFile);
                                                                                                ^

... i am stuck here, since i am not into c++ at all :)

i would like to add support for the USB link provided by chameleon, using the chacolib provided here: https://svn.icomp.de/svn/chaco/chacolib/ ...

**Comment by ricardoquesada** [comment]
I don't have a gentoo to try it, but what Qt projects did you compile? were they Qt 5.x projects?

Did you try from QtCreator? If not, open the `.pro` file from QtCreator and compile from there.

**Comment by ricardoquesada** [comment]
sorry... no idea then :(
I compiled it in an Ubuntu 17.04 without problems with Qt 5.7.1
g++ 6.3.0

As a last resort, try to download and install Qt from the Qt page:
https://info.qt.io/download-qt-for-application-development

That's what I'm using in Ubuntu since the one shipped with it is not updated.

**Comment by mrdudz** [comment]
Am Samstag, 30. September 2017, 05:11:22 CEST schrieb Ricardo Quesada:
> sorry... no idea then :(
> I compiled it in an Ubuntu 17.04 without problems with Qt 5.7.1
> g++ 6.3.0
> 
> As a last resort, try to download and install Qt from the Qt page:
> https://info.qt.io/download-qt-for-application-development
> 
> That's what I'm using in Ubuntu since the one shipped with it is not
> updated.

i'd rather not install things like that from source into my system, it might 
break a lot of things :)

however, i doubt its a Qt issue - looks more like a c++ incompatibility, 
gentoo is still on gcc 5.4

-- 

http://www.hitmen-console.org    http://magicdisk.untergrund.net
http://www.pokefinder.org        http://ar.pokefinder.org

Any sufficiently advanced technology is indistinguishable from magic. 
<Arthur C. Clarke>

**Comment by mrdudz** [comment]
i can build it now, i guess its really about updating GCC

**Comment by ricardoquesada** [comment]
fixed comment by @popmilo
https://gitlab.com/ricardoquesada/vchar64/commit/46dea7fec3fc330a6ae8701f9be0d82381ad8ecf

closing ticket. if there are still build issues, please re-open this ticket, or better yet, open a new one.
