### ISSUE TITLE
right-mouse-button in tile map view

### ISSUE THREAD

**Issue by dobkeratops** [ricardoquesada/vchar64#53]
currently (mac OSX) the right mouse button doesn't seem to do anything in the tile-map editor view,

perhaps this could be assigned to a temporary rectangular select command (e.g. RMB-drag to copy region?), or single click to 'pick tile' (like alt-click in photoshop for selecting colours from the workspace), or even placement of a designated tile (default 'zero'?.. but there could even be a seperate ''bg tile' analogous to having FG/BG paint colours in bitmap editors)

(EDIT - having seen how the 'rectangular-select' tool works, I think this would be the best use of the right-mouse click/drag)

**Comment by ricardoquesada** [comment]
thanks for the suggestion!

**Comment by AndyHOvine** [comment]
An option to set the behaviour of the right mouse button would be neat - I'd like to use it to select tiles on the map :)

**Comment by ricardoquesada** [comment]
fixed. thanks
