### ISSUE TITLE
UI arrangement issues

### ISSUE THREAD

**Issue by superrune** [ricardoquesada/vchar64#56]
Hi! First, great piece of software. Been looking for a C64 tile map editor for the Mac, and this one seems perfect!

I'm trying to work full-screen on my mac, but I've found a couple of issues with re-arranging the UI:
- There doesn't seem to be a way of docking any tabs or windows to the space beneath the main char editor grid.
- When scaling the width of the tilemap and charmap, would it be possible for them both to re-arrange to fit the window?

<img width="1440" alt="screenshot 2018-11-19 at 19 54 42" src="https://user-images.githubusercontent.com/8865466/48728707-01f4a700-ec36-11e8-897d-5226abc0cfdb.png">

**Comment by ricardoquesada** [comment]
works for me. what version of Qt are you using?
I'm using 5.11.2 but IIRC it always worked like this.
![screen shot 2018-11-20 at 8 36 59 am](https://user-images.githubusercontent.com/232330/48771314-d9a19280-ec9f-11e8-8023-1f074c825590.png)

**Comment by superrune** [comment]
Yes, I can also dock it so it fills the entire bottom, but so it fills just the area under the pixel editor. What I cant do is a separate "coloumn" with character, charmap and tilemap.

I'm trying to get rid of empty space on the screen by doing this layout (working on a laptop, to screen space is limited):

![vchar_layout](https://user-images.githubusercontent.com/8865466/48777490-f86d4c80-ecd2-11e8-8d85-8510d1823686.jpg)

**Comment by ricardoquesada** [comment]
ah... yes, I don't think that is possible, at least using "plain" Qt widgets (and that's what I'm using).
I guess if a future Qt version allows it, it should be possible.

**Comment by superrune** [comment]
OK, thanks for the explanation :)

**Comment by ricardoquesada** [comment]
not yet what you want, but I can arrange them a bit better using Qt6
![Screenshot_20220114_105931](https://user-images.githubusercontent.com/232330/149570603-75d299f2-e0fc-44b6-83e0-bfbfec29faec.png)

**Comment by superrune** [comment]
That's perfect, cheers!

**Comment by ricardoquesada** [comment]
great, closing issue then.
