### ISSUE TITLE
Display switches back to hires mode when selecting foreground color from upper row

### ISSUE THREAD

**Issue by hbekel** [ricardoquesada/vchar64#6]
When in multicolor mode and the pen color is set to foreground, the display switches back to single color mode when I click anywhere on the upper row of the color selector. The two multicolors get disabled (greyed out) but the multicolor mode checkbox remains checked, and the state of the GUI seems mixed.

Is the the intented behaviour? I'd expect the display and GUI to remain in multicolor mode and a click on the upper row of the color selector to select the color below (i.e. the color that is "legal" in multicolor mode).

**Comment by hbekel** [comment]
When in multicolor mode and the pen color is set to foreground, the display switches back to single color mode when I click anywhere on the upper row of the color selector. The two multicolors get disabled (greyed out) but the multicolor mode checkbox remains checked, and the state of the GUI seems mixed.

Is the the intented behaviour? I'd expect the display and GUI to remain in multicolor mode and a click on the upper row of the color selector to select the color below (i.e. the color that is "legal" in multicolor mode).

**Comment by ricardoquesada** [comment]
Yes, that is what I tried to do since when you are in multicolor mode, and the foreground color is <8, then the chars are displayed in high-res instead of multicolor.

The `BigcharWidget` and the `charsetWidget` are a kind of "preview" of how it looks.

IIRC, [CharPad](http://csdb.dk/release/?id=101863) also has this same behavior.

**Comment by ricardoquesada** [comment]
@hbekel I'm closing this issue. If you still think it is a bug and we can find another solution for it and I'll reopen it.
