### ISSUE TITLE
Not possible to start up the program with a path to a file to edit

### ISSUE THREAD

**Issue by hugovangalen** [ricardoquesada/vchar64#60]
It would be nice if it were possible to specify the project file when opening vchar64 from the command line. I.e. like
```
~$ vchar64 /path/to/file.vchar64proj
```

It would save a few clicks (= time) when wanting to edit a file.

**Comment by ricardoquesada** [comment]
I'll release a new version somewhere in the near future, but for the time being, you'll have to compile it yourself.

**Comment by hugovangalen** [comment]
Great! Thanks for the update!
