### ISSUE TITLE
type limits

### ISSUE THREAD

**Issue by Lobotomius** [ricardoquesada/vchar64#8]
importkoaladialog.cpp: In member function ‘bool ImportKoalaDialog::convert()’:
importkoaladialog.cpp:579:27: error: comparison is always true due to limited range of data type [-Werror=type-limits]
         Q_ASSERT(colorRAM >=0 && colorRAM<16 && "Invalid colorRAM");

**Comment by ricardoquesada** [comment]
Thanks. are you a bot?

**Comment by Lobotomius** [comment]
nah man

**Comment by Lobotomius** [comment]
would i know if i was?

**Comment by ricardoquesada** [comment]
fixed. thanks.
